### ISSUE TITLE
Implementar as classes Player e Pair

### ISSUE THREAD

**Issue by Emiliemorais** [DAS1-2016/Truco#2]
* Um objeto de Pair possui um id e um dicionário com 2 players
* Um Player possui um nome, uma mão (hand) e um jogo (game)
* Um Player deve poder jogar uma carta
* Um Player deve poder pedir truco, seis e etc
* Um Player deve poder atualizar a sua mão (hand)

**Comment by keliunb** [comment]
issue implemented
