### ISSUE TITLE
Implementar a classe MatchState e seus estados 

### ISSUE THREAD

**Issue by Emiliemorais** [DAS1-2016/Truco#5]
* NormalMatch (Rodada vale 1 ponto)
* TrucoMatch (Rodada vale 3 pontos)
* SixMatch (Rodada vale 6 pontos)
* NineMatch (Rodada vale 9 pontos)
* TwelveMatch (Rodada vale 12 pontos)
* TiedMatch (Rodada cangada)
* Para cada MatchState deve ser possível:
     * Encerrar o match atribuindo os pontos referentes ao estado (state)
     * Passar para o próximo estado (matchstate)

**Comment by keliunb** [comment]
issue implemented
